"""create_initial_tables

Revision ID: 313b55bd4b15
Revises: 
Create Date: 2025-05-16 16:23:57.681919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '313b55bd4b15'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cards_id', table_name='cards')
    op.drop_index('ix_cards_name', table_name='cards')
    op.drop_index('ix_cards_scryfall_id', table_name='cards')
    op.drop_table('cards')
    op.add_column('card_definitions', sa.Column('image_data_small', sa.LargeBinary(), nullable=True))
    op.add_column('card_definitions', sa.Column('image_data_normal', sa.LargeBinary(), nullable=True))
    op.add_column('card_definitions', sa.Column('image_data_large', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card_definitions', 'image_data_large')
    op.drop_column('card_definitions', 'image_data_normal')
    op.drop_column('card_definitions', 'image_data_small')
    op.create_table('cards',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('scryfall_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('set_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('collector_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('quantity_normal', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity_foil', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_added', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('date_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cards_pkey')
    )
    op.create_index('ix_cards_scryfall_id', 'cards', ['scryfall_id'], unique=True)
    op.create_index('ix_cards_name', 'cards', ['name'], unique=False)
    op.create_index('ix_cards_id', 'cards', ['id'], unique=False)
    # ### end Alembic commands ###
